services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - etl-postgres-data:/var/lib/postgresql/data
    networks:
      - etl-network

  airflow:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow
    depends_on:
    - postgres
    - statsd-exporter
    volumes:
      - etl-containers-shared-data:/app/data         # Shared Volume between containers for data
      - etl-data-airflow:/opt/airflow                # Volume for persistence of Airflow data
      - ./airflow/dags:/opt/airflow/dags             # Mount the local folder 'dags' in the container
      - ./preparator:/opt/airflow/preparator         # Mount the local folder 'preparator' in the container
    ports:
      - "8080:8080"
    networks:
      - etl-network
    restart: always

  # exporter metrics Airflow -> Prometheus
  statsd-exporter:
    image: prom/statsd-exporter:latest
    container_name: statsd-exporter
    depends_on:
    - postgres
    ports:
      - "9102:9102"
    networks:
      - etl-network

#  Microservice monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - etl-prometheus-data:/etc/prometheus                         
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  
    ports:
      - "9090:9090"
    networks:
      - etl-network
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - etl-grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - etl-network
    restart: always

# Microservices
  extract-csv-service:
    build:
      context: ./services
      dockerfile: extract-csv-service/Dockerfile
    container_name: extract-csv-service
    volumes:
      - etl-containers-shared-data:/app/data
    ports:
      - "5001:5001"
    networks:
      - etl-network
    restart: always

  clean-nan-service:
    build:
      context: ./services
      dockerfile: clean-nan-service/Dockerfile
    container_name: clean-nan-service
    volumes:
      - etl-containers-shared-data:/app/data
    ports:
      - "5002:5002"
    networks:
      - etl-network
    restart: always

  get-columns-service:
    build:
      context: ./services
      dockerfile: get-columns-service/Dockerfile
    container_name: get-columns-service
    volumes:
      - etl-containers-shared-data:/app/data
    ports:
      - "5003:5003"
    networks:
      - etl-network
    restart: always

  delete-columns-service:
    build:
      context: ./services
      dockerfile: delete-columns-service/Dockerfile
    container_name: delete-columns-service
    volumes:
      - etl-containers-shared-data:/app/data
    ports:
      - "5004:5004"
    networks:
      - etl-network
    restart: always

  extract-sql-service:
    build:
      context: ./services
      dockerfile: extract-sql-service/Dockerfile
    container_name: extract-sql-service
    volumes:
      - etl-containers-shared-data:/app/data
    ports:
      - "5005:5005"
    networks:
      - etl-network
    restart: always

  extract-api-service:
    build:
      context: ./services
      dockerfile: extract-api-service/Dockerfile
    container_name: extract-api-service
    volumes:
      - etl-containers-shared-data:/app/data
    ports:
      - "5006:5006"
    networks:
      - etl-network
    restart: always

  extract-excel-service:
    build:
      context: ./services
      dockerfile: extract-excel-service/Dockerfile
    container_name: extract-excel-service
    volumes:
      - etl-containers-shared-data:/app/data
    ports:
      - "5007:5007"
    networks:
      - etl-network
    restart: always

  join-datasets-service:
    build:
      context: ./services
      dockerfile: join-datasets-service/Dockerfile
    container_name: join-datasets-service
    volumes:
      - etl-containers-shared-data:/app/data
    ports:
      - "5008:5008"
    networks:
      - etl-network
    restart: always

  load-data-service:
    build:
      context: ./services
      dockerfile: load-data-service/Dockerfile
    container_name: load-data-service
    volumes:
      - etl-containers-shared-data:/app/data
    ports:
      - "5009:5009"
    networks:
      - etl-network
    restart: always

  data-quality-service:
    build:
      context: ./services
      dockerfile: data-quality-service/Dockerfile
    container_name: data-quality-service
    volumes:
      - etl-containers-shared-data:/app/data
    ports:
      - "5010:5010"
    networks:
      - etl-network
    restart: always

  outlier-detection-service:
    build:
      context: ./services
      dockerfile: outlier-detection-service/Dockerfile
    container_name: outlier-detection-service
    volumes:
      - etl-containers-shared-data:/app/data
    ports:
      - "5011:5011"
    networks:
      - etl-network
    restart: always


networks:
  etl-network:
    driver: bridge

volumes:
  etl-containers-shared-data:
  etl-postgres-data:
  etl-data-airflow:
  etl-grafana-data:
  etl-prometheus-data: